// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoP2.Infrastructure.Data.Context;

#nullable disable

namespace ProjetoP2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260608012756_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.AppointmentClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateAppointment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("AppointmentClinics", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VetClinics", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.AppointmentRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateAppointment")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("VetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("OwnerRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.PetRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Castrated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Community")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Microchipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MicrochippedNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PetRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.AppointmentClinic", b =>
                {
                    b.HasOne("ProjetoP2.Clinic.Domain.Entities.VetClinic", "Vet")
                        .WithMany("Appointments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("VetClinicId");

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Clinic.Domain.ValueObjects.CRMV", "CRMV", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("CRMV");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("CRMV")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("OwnerRegisterId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("OwnerRegisterId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("OwnerRegisterId");

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.PetRegister", b =>
                {
                    b.HasOne("ProjetoP2.Register.Domain.Entities.OwnerRegister", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.City", "City", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("City");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Color");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Sex", "Sex", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Sex");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Specie", "Specie", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Specie");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.State", "State", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)")
                                .HasColumnName("State");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PetRG", "PetRG", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("PetRG");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.Navigation("City");

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PetRG");

                    b.Navigation("Sex")
                        .IsRequired();

                    b.Navigation("Specie")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
