// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoP2.Clinic.Infrastructure.Data;

#nullable disable

namespace ProjetoP2.Migrations
{
    [DbContext(typeof(ClinicDBContext))]
    [Migration("20260528235224_INITIALMIGRATIONCLINIC")]
    partial class INITIALMIGRATIONCLINIC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.AppointmentClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateAppointment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("AppointmentClinics", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VetClinics", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.AppointmentClinic", b =>
                {
                    b.HasOne("ProjetoP2.Clinic.Domain.Entities.VetClinic", "Vet")
                        .WithMany("Appointments")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.OwnsOne("ProjetoP2.Clinic.Domain.ValueObjects.CRMV", "CRMV", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CRMV");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");

                            b1.HasKey("VetClinicId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("VetClinicId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("VetClinicId");

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("CRMV")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoP2.Clinic.Domain.Entities.VetClinic", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
