<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Clinic\Infrastructure\Data\**" />
    <Compile Remove="Infrastructure\Auth\**" />
    <Compile Remove="Infrastructure\CrossCutting\**" />
    <Compile Remove="Infrastructure\Messaging\**" />
    <Compile Remove="Infrastructure\Observability\**" />
    <Compile Remove="Infrastructure\Repositories\**" />
    <Compile Remove="Interface\Controllers\**" />
    <Compile Remove="Interface\Filters\**" />
   
    <Compile Remove="Shared\Data\**" />
    <Content Remove="Clinic\Infrastructure\Data\**" />
    <Content Remove="Infrastructure\Auth\**" />
    <Content Remove="Infrastructure\CrossCutting\**" />
    <Content Remove="Infrastructure\Messaging\**" />
    <Content Remove="Infrastructure\Observability\**" />
    <Content Remove="Infrastructure\Repositories\**" />
    <Content Remove="Interface\Controllers\**" />
    <Content Remove="Interface\Filters\**" />

    <Content Remove="Shared\Data\**" />
    <EmbeddedResource Remove="Clinic\Infrastructure\Data\**" />
    <EmbeddedResource Remove="Infrastructure\Auth\**" />
    <EmbeddedResource Remove="Infrastructure\CrossCutting\**" />
    <EmbeddedResource Remove="Infrastructure\Messaging\**" />
    <EmbeddedResource Remove="Infrastructure\Observability\**" />
    <EmbeddedResource Remove="Infrastructure\Repositories\**" />
    <EmbeddedResource Remove="Interface\Controllers\**" />
    <EmbeddedResource Remove="Interface\Filters\**" />

    <EmbeddedResource Remove="Shared\Data\**" />
    <None Remove="Clinic\Infrastructure\Data\**" />
    <None Remove="Infrastructure\Auth\**" />
    <None Remove="Infrastructure\CrossCutting\**" />
    <None Remove="Infrastructure\Messaging\**" />
    <None Remove="Infrastructure\Observability\**" />
    <None Remove="Infrastructure\Repositories\**" />
    <None Remove="Interface\Controllers\**" />
    <None Remove="Interface\Filters\**" />

    <None Remove="Shared\Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
