<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Clinic\Infrastructure\Data\**" />
   
    <Compile Remove="Shared\Data\**" />
    <Content Remove="Clinic\Infrastructure\Data\**" />

    <Content Remove="Shared\Data\**" />
    <EmbeddedResource Remove="Clinic\Infrastructure\Data\**" />

    <EmbeddedResource Remove="Shared\Data\**" />
    <None Remove="Clinic\Infrastructure\Data\**" />

    <None Remove="Shared\Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\DTOs\" />
    <Folder Include="Application\Interfaces\" />
    <Folder Include="Application\Mappings\" />
    <Folder Include="Application\UseCases\" />
    <Folder Include="Application\Services\" />
    <Folder Include="Domain\DomainEvents\" />
    <Folder Include="Domain\IRepositories\" />
    <Folder Include="Domain\ValueObjects\" />
    <Folder Include="Infrastructure\CrossCutting\IoC\" />
    <Folder Include="Infrastructure\CrossCutting\Logging\" />
    <Folder Include="Infrastructure\CrossCutting\Exceptions\" />
    <Folder Include="Infrastructure\Auth\" />
    <Folder Include="Infrastructure\Messaging\Consumers\" />
    <Folder Include="Infrastructure\Messaging\Events\" />
    <Folder Include="Infrastructure\Messaging\Producers\" />
    <Folder Include="Infrastructure\Observability\" />
    <Folder Include="Infrastructure\Repositories\" />
    <Folder Include="Interface\Controllers\" />
    <Folder Include="Interface\Filters\" />
    <Folder Include="Migrations\" />
    <Folder Include="Register\Domain\Exceptions\" />
  </ItemGroup>

</Project>
