// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoP2.Register.Infrastructure.Data;

#nullable disable

namespace ProjetoP2.Migrations.RegisterDB
{
    [DbContext(typeof(RegisterDBContext))]
    [Migration("20260529000601_INITIALMIGRATIONCLINIC")]
    partial class INITIALMIGRATIONCLINIC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.AppointmentRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateAppointment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppointmentRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OwnerRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.PetRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Castrated")
                        .HasColumnType("boolean");

                    b.Property<bool>("Community")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Microchipped")
                        .HasColumnType("boolean");

                    b.Property<int?>("MicrochippedNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PetRegisters", (string)null);
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("OwnerRegisterId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");

                            b1.HasKey("OwnerRegisterId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("OwnerRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("OwnerRegisterId");

                            b1.ToTable("OwnerRegisters");

                            b1.WithOwner()
                                .HasForeignKey("OwnerRegisterId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.PetRegister", b =>
                {
                    b.HasOne("ProjetoP2.Register.Domain.Entities.OwnerRegister", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.City", "City", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Color");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Sex", "Sex", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Sex");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.Specie", "Specie", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Specie");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Register.Domain.ValueObjects.State", "State", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("State");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.OwnsOne("ProjetoP2.Shared.ValueObjects.PetRG", "PetRG", b1 =>
                        {
                            b1.Property<Guid>("PetRegisterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PetRG");

                            b1.HasKey("PetRegisterId");

                            b1.ToTable("PetRegisters");

                            b1.WithOwner()
                                .HasForeignKey("PetRegisterId");
                        });

                    b.Navigation("City");

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PetRG");

                    b.Navigation("Sex")
                        .IsRequired();

                    b.Navigation("Specie")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("ProjetoP2.Register.Domain.Entities.OwnerRegister", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
